__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


а) количество столбцов не соответствует количеству строк другой матрицы, ни в одном случае

б) произведение AB возможно (2х3), BA - нет. 

в) Оба произведения возможны (8х8 и 3х3)

г) оба произведения возможны. (обе 4х4)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


сумма = ([5, -3], 
         [3, 5])
         
произведение = ([4, -11],
               [12, 3])

In [4]:
import numpy as np

In [5]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [6]:
A+B

array([[ 5, -3],
       [ 3,  5]])

In [8]:
np.dot(A,B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
   

3A= ([[3,21],      2B=([[0, 10],    4C = ([[8, -16],
     [9, -18]])        [4, -2]])          [4, 4]])

3A-2B+4C = ([[11, -5],
            [9, -12]])

In [9]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [11]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

A = ([[4, 1],
     [5, -2],
     [2,3]])

At = ([[4, 5, 2],
      1, -2, 3])

In [ ]:
AAt = ([[17, 18, 11],
       [18, 29, 4],
       [11, 4, 13]])


AtA = ([[45, 0],
       [0, 14]])

In [14]:
A = np.array([[4, 1], [5, -2], [2,3]])

At = A.T

A, At

(array([[ 4,  1],
        [ 5, -2],
        [ 2,  3]]),
 array([[ 4,  5,  2],
        [ 1, -2,  3]]))

In [16]:
np.dot(A,At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [17]:
np.dot(At, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [19]:
def matrix_mult(A,B):  
    m = A.shape[0]
    n1 = A.shape[1]
    n2 = B.shape[0]
    k = B.shape[1]
    if n1 == n2: 
        n = n1
    else:
        print(f'произведение не определено')
        return False
  
    C = np.zeros((m,k))
    for i in range(m):
        for j in range(k):
            for l in range(n): 
                C[i,j] +=A[i,l]*B[l,j] 
        return C

### Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$




In [ ]:
a) sin*sin - (-cos)*cos = sin^2 + cos^2 = 1
б) матрица треугольная, поэтому определитель 4*5*9 = 180
в) 1*5*9 + 2*6*7 + 4*8*3 - 7*5*3 - 4*2*9 - 1*8*6 = 45+84+96 - 105-72-48= 225 - 225 = 0

In [27]:
x=1 #условно

A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])

B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.linalg.det(A), np.linalg.det(B), np.linalg.det(C)

(1.0, 180.0, -9.51619735392994e-16)

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


а) 4*4 = 16

б) 4

в) 4*2 = 8

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



найдем определитель

-2*(-14)*13 +7*6*(-3) + 4*7(-3) - (-3)*(-14)*(-3) - 4*7*13 - (-2)*7*6 = 364 - 126 - 84 + 126 - 364 + 84 = 0
Если определитель равен нолю, значит матрица вырожденная.


In [32]:
A = np.array([[-2, 7, -3], 
             [4, -14, 6],
             [-3, 7, -13]])

np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) отбросим 3 строку, т.к. это сумма 1 и 2. оставшиеся строки линейно не зависят друг от друга, значит ранг 2.
б) отбросим 3 строку, т.к. это сумма 1 и 2. оставшиеся строки линейно не зависят друг от друга, значит ранг 3.

In [33]:
A = np.array([[1,2,3],
            [1,1,1],
            [2,3,4]])
np.linalg.matrix_rank(A)

2

In [34]:
B = np.array([[0,0,2,1],
               [0,0,2,2],
               [0,0,4,3],
               [2,3,5,6]])
np.linalg.matrix_rank(B)

3