__Задача 1__

Объясняемая переменная `y` зависит от двух категориальных факторов `A` и `B`, причём фактор `A` имеет 3 уровня, а фактор `B` - 4 уровня. Результаты наблюдений приведены в таблице:

```
y = [[2.68, 3.29, 2.88, 4.45],
     [4.12, 4.96, 5.09, 5.22],
     [5.52, 4.50, 5.42, 5.29]]
```

С помощью двухфакторного дисперсионного анализа проверьте влияние каждого из факторов на переменную `y`.

In [4]:
import numpy as np
from scipy import stats

In [5]:
Y = np.array([[2.68, 3.29, 2.88, 4.45],
     [4.12, 4.96, 5.09, 5.22],
     [5.52, 4.50, 5.42, 5.29]])

print(Y)

[[2.68 3.29 2.88 4.45]
 [4.12 4.96 5.09 5.22]
 [5.52 4.5  5.42 5.29]]


In [7]:
m = Y.shape[0]
k = Y.shape[1]
n = m * k
m, k, n

(3, 4, 12)

In [9]:
yk_mean = Y.mean(axis=0)
ym_mean = Y.mean(axis=1)
yk_mean, ym_mean

(array([4.10666667, 4.25      , 4.46333333, 4.98666667]),
 array([3.325 , 4.8475, 5.1825]))

In [11]:
S_a = k * ((yk_mean - Y.mean())**2).sum()
S_b = m * ((ym_mean - Y.mean())**2).sum()
S_w = ((Y - Y.mean(axis=0) - Y.mean(axis=1).reshape(3,1) + Y.mean())**2).sum()

S_a, S_b, S_w

(1.7842222222222253, 5.880537499999999, 1.9298833333333332)

In [13]:
sigma2_a = S_a / (m - 1)
sigma2_b = S_b / (k - 1)
sigma2_w = S_w / ((k - 1) * (m - 1))

sigma2_a, sigma2_b, sigma2_w

(0.8921111111111126, 1.9601791666666664, 0.3216472222222222)

In [16]:
alpha = 0.05

F_a = sigma2_a / sigma2_w
k1_a = m - 1
k2_a = n - m
t_a = stats.f.ppf(1 - alpha, k1_a, k2_a)

t_a

4.25649472909375

In [19]:
F_a = sigma2_a / sigma2_w
F_a

2.7735700776385497

Значение статистики не попало в критическую область (4,26; +inf), значит влияние фактора A не очень значимо

In [17]:
F_b = sigma2_b / sigma2_b
k1_b = k - 1
k2_b = n - k
t_b = stats.f.ppf(1 - alpha, k1_b, k2_b)

t_b

4.06618055135116

In [20]:
F_b = sigma2_b / sigma2_w
F_b

6.094189631497586

Значение статистики попало в критическую область (4,07; +inf), значит влияние фактора B значимо